### ISSUE TITLE
xvpictoppm manual renamed in cmake build

### ISSUE THREAD

**Issue by sthen** [jasper-software/xv#1]
In the cmake build, the manual for xvpictoppm is installed as xvp2p.1 following the name of the file in the repo. Simplest fix might be to just rename it rather than special-case it in CMakeLists.

**Comment by pghmcfc** [comment]
Renaming it to xvpictoppm.1 in the repo and adjusting the CMakeLists / Makefile looks like the best option to me.

**Comment by mdadams** [comment]
I agree that renaming the file is probably the best way to go.  I have made this change in commit 9b6f83d0cd9fabb391a5d956853c0a7dccad2667.
