### ISSUE TITLE
bb0cebf breaks classic Makefile builds

### ISSUE THREAD

**Issue by mal359** [jasper-software/xv#14]
Hello,

`bits/xv_rev` and `bits/xv_ver` are still referenced in the in-tree Makefile.

While I'm here, I've also included a patch which dynamically links to JasPer when building with the classic Makefile.

[Makefile.diff.txt](https://github.com/jasper-software/xv/files/13646621/Makefile.diff.txt)
[xvdflt.diff.txt](https://github.com/jasper-software/xv/files/13646622/xvdflt.diff.txt)

**Comment by mdadams** [comment]
Building xv with Make is no longer supported.  All of the makefiles are slated for removal.  Please switch to using CMake.
