### ISSUE TITLE
Silence -Wdeprecated-declarations on xvtiff.c

### ISSUE THREAD

**Issue by mal359** [jasper-software/xv#16]
[tiff_warnings.diff.txt](https://github.com/jasper-software/xv/files/13656938/tiff_warnings.diff.txt)

**Comment by mdadams** [comment]
If you are proposing a code change, please submit a pull request.

**Comment by mdadams** [comment]
It appears that this issue was resolved in commit 02dec96.  So, I am closing this issue.
