### ISSUE TITLE
Splash screen?

### ISSUE THREAD

**Issue by oldpink** [jasper-software/xv#9]
First, I wanted to say a quick thanks for reviving the previously stagnant XV, still one of the best compact open source image viewers.
The thing that I wanted to make as a request has nothing to do with functionality, but with esthetics, namely the opening splash screen that shows the version as the old 3.10a, even though it is in fact now revised to version 4.1.1.
I'm sure that you would like having that splash reflect that revision change.
Thanks again.

**Comment by mdadams** [comment]
You are welcome to submit a pull request to fix this.

**Comment by oldpink** [comment]
I'm embarrassed to say that I have no idea how to submit one.
I also don't have a fixed splash screen.
Sorry
:(

**Comment by tanabi** [comment]
I may go take a look at this, though I suspect the splash screen is a pre-render and those numbers are baked into it.  Hopefully I'm wrong though!

**Comment by jn64** [comment]
Looks like the version text is [pre-rendered (as X bitmap?)](https://github.com/jasper-software/xv/blob/ad9e5fe3afe469fd4eba3c10984c6b91907e16fd/src/bits/xv_ver) and drawn in the splash screen here (along with the revision date, and the copyright statement before it):

https://github.com/jasper-software/xv/blob/ad9e5fe3afe469fd4eba3c10984c6b91907e16fd/src/xvdflt.c#L108-L118

A small project for those interested would be to convert the pre-rendered parts to strings like these other parts, which would make it easier to update:

https://github.com/jasper-software/xv/blob/ad9e5fe3afe469fd4eba3c10984c6b91907e16fd/src/xvdflt.c#L120-L132

**Comment by oldpink** [comment]
That sounds like the logical solution.
I have zero programming skills, but there are probably others who do.
I just wish that your revived repository were getting more notice so that others could lend you a hand.
Thanks

**Comment by mdadams** [comment]
Hopefully people who are interested in the repository will star it, as this will likely help to increase its visibility.  Currently, the repository only has 5 stars.

**Comment by tanabi** [comment]
I did my part and starred it.  I may have time this weekend to do the conversion proposed by jn64.

**Comment by galenhuntington** [comment]
FWIW I recently [added this project to nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/xv/default.nix).  That may in time bring more attention.

**Comment by jn64** [comment]
A downside of this is losing the look of the pre-rendered text.
I believe it is set in the Tekton font based on
architect Frank Ching's handwriting. Somehow it fits
with the floating fish and general weirdness of xv.

The other text that is drawn from strings uses a 5x9 pixel font
with less personality.

I still think it's worth changing for ease of maintenance.
Just wanted to note for posterity :)

**Comment by mdadams** [comment]
> FWIW I recently [added this project to nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/xv/default.nix). That may in time bring more attention.

@galenhuntington Thanks.  I think that that this will help.

**Comment by tanabi** [comment]
@mdadams You can close this one out too!  Thanks for merging it.

**Comment by oldpink** [comment]
Wow!
I just compiled/installed it and it looks great.
Thanks a log...closing.
